
services:
  mongo-db:
    image: mongo:latest 
    container_name: mongo_test_db 
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: tuouser
      MONGO_INITDB_ROOT_PASSWORD: tuapassword
      
    ports:
      - "27017:27017"
      
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local 